### PR TITLE
Y24-200 - Run volume tracking bug

### LINKED ISSUE #1819: Y24-200 - [BUG] - Unable to add a library several times to the same run.
**Describe the bug**
Hi, I encountered a bug this week setting up a run. I had a Sequel II run that had the same libraries being run multiple times. Due to the volume tracking fields I was unable to set the run up in one go as the available volume for each library was being deducted with the first instance on the run even if edited to a the volume used for each well being sequenced.
The run in question is TRACTION-RUN-1377.
I managed to work around this issue by creating the run with each library appearing once and then editing each run to add the duplicate library and then editing again for the triplicate. It may be rare that his functionality would be used on the Revio but it should be possible to sequence the sample library/pool more than once on the same run. Maybe even being able to override once the volume has hit zero. At this point in the process we will physically have a library to load so should not be prevented from loading if library volume is 0 (but this is the best point currently to register volume of library used).
In this particular instance I have used the entire library that was available and then split out the resulting reaction mix across 2 or more cells to use up the remaining library in the most efficient way possible. So, I would be happy to set the volume correctly on the first cell for the library but for any additional cells from the same library would not need further updating.
Next week I will also be loading some of the same libraries, at this moment in time I have just estimated how much library I have used for each cell so that I don't get a zero volume error when I try to create a run. However If we decided to not proceed any further the remaining library volumes would be incorrect (without further editing).

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

### PR DESCRIPTION
**Pull request by BenTopping**
Closes #1819 

#### Changes proposed in this pull request

- Updates the way available_volume is calculated for Libraries and Pools in a PacBio run
- Updates the way available_volume is shown in PacbioRunWellEdit.
- Updates how available_volume and volume are calculated in the createdUsedAliquot function.

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

**Review by SHIV5T3R — APPROVED** [review]

File: src/components/labware/PacbioRunWell.vue [hunk 1]
```diff
@@ -196,17 +196,20 @@ const updateUsedAliquotSource = async (barcode) => {
...
-        volume: 0,
-      }),
-  )
+  const used_aliquot = createUsedAliquot({
+    ...tubeContent,
+    source_id: tubeContent.id,
+    id: null,
+    volume: available_volume,
+    available_volume,
+  })
```
Comment (seenanair) [inline src/components/labware/PacbioRunWell.vue:212]: Just a thought: now that we are dynamically calculating available_volume every time, would it be better to refactor the createUsedAliquot function to handle the calculation of available_volume internally so we don't need to repeat two calls? This would make the code cleaner.

File: src/stores/pacbioRunCreate.js [hunk 2]
```diff
@@ -527,55 +518,52 @@ export const usePacbioRunCreateStore = defineStore('pacbioRunCreate', {
...
-        // If its a new aliquot we need to add the volume back in to the total available volume
-        // because it was removed as part of the library_used_aliquots volume but it should be available in this instance of aliquot
-        total_available_volume = parseFloat(total_available_volume) + parseFloat(volume)
-      }
+      let total_available_volume = (
+        available_volume +
+        original_aliquot_volume -
+        used_aliquots_volume +
+        parseFloat(volume)
+      ).toFixed(2)
```
Comment (seenanair) [inline src/stores/pacbioRunCreate.js:563]: Would it be better to add a comment to describe a little more as this bit complex and confusing for someone looking at it in future.

File: tests/unit/stores/utilities/pool.spec.js [hunk 3]
```diff
@@ -28,11 +30,7 @@ describe('pool', () => {
       expect(usedAliquot.volume).toBe(10)
       expect(usedAliquot.concentration).toBe(5)
       expect(usedAliquot.insert_size).toBe(1)
-    })
-    it('correctly sets the default volume when initialiseToAvailableVolume is provided', () => {
-      const initialiseToAvailableVolume = () => '20'
-      const usedAliquot = createUsedAliquot({ volume: 10 }, initialiseToAvailableVolume)
-      expect(usedAliquot.volume).toBe(20)
+      expect(usedAliquot.available_volume).toBe(10)
     })
```
Comment (seenanair) [inline tests/unit/stores/utilities/pool.spec.js:34]: Is there a test already exists either in unit or e2e to check the context where we are adding the same library twice in a run, to ensure that this fix is covered? If not, would it be better to add one?

**Review by seenanair — COMMENTED** [review]
Great fix. 👍 
Just added a few thoughts.
Also, I haven't tested it locally.

File: src/components/labware/PacbioRunWell.vue (hunk 1 above)
Comment (BenTopping) [reply src/components/labware/PacbioRunWell.vue:212]: available_volume requires the run store state so we need to pass the whole state into the createUsedAliquot function. I am also not sure available_volume should live in the aliquot as its actually a mixture of the aliquot data and library/pool data but couldn't find a better place to put it.

Comment (seenanair) [reply src/components/labware/PacbioRunWell.vue:212]: Ok, hmm, that makes sense. yes, it looks like getAvailableVolumeForAliquot needs lots of store state variables.

File: tests/unit/stores/utilities/pool.spec.js (hunk 3 above)
Comment (BenTopping) [reply tests/unit/stores/utilities/pool.spec.js:34]: Yes there is an e2e test for it

**Review by seenanair — APPROVED** [review]
