### PR TITLE
DPL-594 Pacbio views pagination

### LINKED ISSUE #1003: DPL-594 [BUG] Traction: Search functionality breaks or takes longer to search the matching records on the Pacbio 'Runs' tab.
**Describe the bug**
Search functionality breaks or takes longer to search the matching records on the Pacbio 'Runs' tab.
image

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to Pacbio > Runs from https://traction.psd.sanger.ac.uk/#/dashboard
2. Enter run 'Name' in the filter search box available above the record list.

**Expected behaviour**
System should display the records matching the entered text.

**Actual/Existing behaviour**
System does not perform the search or takes longer to display the matching records from the list.

### PR DESCRIPTION
**Pull request by BenTopping**
Current work updating pacbio views to include new filtering capabilities with the aim of improving performance

NOTE: Easy fix for current failing cypress tests. They are caused by the datafetcher request not being stubbed when navigating to the runs page

Closes #1003 

Changes proposed in this pull request:

* Added filterCard component to all pacbio index views
* Updated various actions to support new pagination
* Added DataFetcher component to all pacbio index views.
* Fixed bug in pacbio samples where 'show details' was not displaying anything

### CODE REVIEW

File: src/store/traction/pacbio/plates/actions.js [hunk 1]
```diff
@@ -1,16 +1,20 @@
 import handlePromise from '@/api/PromiseHelper'
 
-const setPlates = async ({ commit, getters }) => {
+const setPlates = async ({ commit, getters }, filter) => {
   let request = getters.getPlates
-  let promise = request.get({ include: 'wells.materials' })
+  let promise = request.get({
+    include: 'wells.materials',
+    filter: filter,
```
Comment (stevieing) [inline src/store/traction/pacbio/plates/actions.js:7]: this can just be filter

File: src/store/traction/pacbio/libraries/actions.js [hunk 2]
```diff
@@ -45,32 +45,36 @@ const deleteLibraries = async ({ getters }, libraryIds) => {
...
+  let promise = request.get({
+    include: 'request,tag,tube,pool',
+    filter: filter,
+  })
+  let response = await handleResponse(promise)
+
+  const { success, data: { data, included = [] } = {}, errors = [] } = response
+  const { tubes, tags, requests, pools } = groupIncludedByResource(included)
 
+  if (success) {
```
Comment (stevieing) [inline src/store/traction/pacbio/libraries/actions.js:59]: lots going on here. Maybe a bit more explanation. Do we do anything similar elsewhere?

File: src/store/traction/pacbio/plates/actions.js [hunk 3]
```diff
@@ -1,16 +1,20 @@
...
+  })
   let response = await handlePromise(promise)
 
   if (response.successful && !response.empty) {
     let plates = response.deserialize.plates
```
Comment (stevieing) [inline src/store/traction/pacbio/plates/actions.js:12]: I think at some point we can look at removing the usage of deserialize as I think it can cause all sorts of problems with recursion.

File: src/store/traction/pacbio/libraries/actions.js [hunk 4]
```diff
@@ -45,32 +45,36 @@ const deleteLibraries = async ({ getters }, libraryIds) => {
...
-      // the libraries
-      const {
-        tag: { group_id: tag_group_id } = { group_id: null },
-        // should be request: { sample: { name } }
-        request: { sample_name } = { sample_name: null },
-        tube: { barcode } = { barcode: null },
-      } = library
-      return { ...library, tag_group_id, sample_name, barcode }
-    })
+  let promise = request.get({
```
Comment (stevieing) [inline src/store/traction/pacbio/libraries/actions.js:50]: This is so much clwaner. you can change the lets to const

File: src/store/traction/pacbio/libraries/actions.js [hunk 5]
```diff
@@ -45,32 +45,36 @@ const deleteLibraries = async ({ getters }, libraryIds) => {
...
+    include: 'request,tag,tube,pool',
+    filter: filter,
```
Comment (stevieing) [inline src/store/traction/pacbio/libraries/actions.js:52]: it can just be filter

File: src/store/traction/pacbio/pools/actions.js [hunk 6]
```diff
@@ -11,6 +11,7 @@ const setPools = async ({ commit, getters }) => {
       tags: 'group_id',
       libraries: 'request,tag,run_suitability',
     },
+    filter: filter,
```
Comment (stevieing) [inline src/store/traction/pacbio/pools/actions.js:14]: this can just be filter

File: src/store/traction/pacbio/requests/actions.js [hunk 7]
```diff
@@ -1,15 +1,18 @@
 import handlePromise from '@/api/PromiseHelper'
 import { handleResponse } from '@/api/ResponseHelper'
 
-const setRequests = async ({ commit, getters }) => {
+const setRequests = async ({ commit, getters }, filter) => {
   let request = getters.requestsRequest
-  let promise = request.get()
+  let promise = request.get({ filter: filter })
```
Comment (stevieing) [inline src/store/traction/pacbio/requests/actions.js:6]: this can just be filter

File: src/store/traction/pacbio/runs/actions.js [hunk 8]
```diff
@@ -18,17 +19,18 @@ const buildWell = ({ state }, position) => {
   }
 }
 
-const setRuns = async ({ commit, getters }) => {
-  let request = getters.runRequest
-  let promise = request.get({ include: 'plate.wells.pools.tube' })
-  let response = await handlePromise(promise)
+const fetchPacbioRuns = async ({ commit, getters }, filter) => {
```
Comment (stevieing) [inline src/store/traction/pacbio/runs/actions.js:22]: Much better as we don't need to return all the includes

File: src/store/traction/pacbio/runs/actions.js [hunk 9]
```diff
@@ -18,17 +19,18 @@ const buildWell = ({ state }, position) => {
...
+  const request = getters.runRequest
+  const promise = request.get({ filter: filter })
```
Comment (stevieing) [inline src/store/traction/pacbio/runs/actions.js:24]: this can just be filter

**Review by stevieing — CHANGES_REQUESTED** [review]
Nice. Great to reuse some of those components. Just a few minor changes put looks pretty good. I will run a check locally to see if it is working correctly.

**Review by stevieing — COMMENTED** [review]
I have checked it locally and it all seems to work really nicely. I guess we are only gonng to notice performance improvements on UAT. I did notice that the filter takes up quite a lot of space so was wondering if there was any way to make it a bit smaller or even for users to click on a filter button to open it?

File: src/store/traction/pacbio/libraries/actions.js (hunk 2 above)
Comment (BenTopping) [reply src/store/traction/pacbio/libraries/actions.js:59]: Couldn't find a similar method but added a small explanation.

File: src/store/traction/pacbio/plates/actions.js (hunk 3 above)
Comment (BenTopping) [reply src/store/traction/pacbio/plates/actions.js:12]: Yep agreed

**Review by stevieing — APPROVED** [review]

File: tests/e2e/specs/pacbio/pacbio_runs_view.cy.js [hunk 10]
```diff
@@ -1,9 +1,13 @@
 describe('Pacbio Runs view', () => {
   it('Visits the pacbio runs url', () => {
-    cy.intercept('/v1/pacbio/runs?include=plate.wells.pools.tube', {
+    cy.intercept('/v1/pacbio/runs', {
```
Comment (stevieing) [inline tests/e2e/specs/pacbio/pacbio_runs_view.cy.js:3]: excellent. This wil make it so much faster ...

**Review by stevieing — APPROVED** [review]
